[env:bluepill_f103c8]
platform = ststm32@~8.0.0
board = bluepill_f103c8
framework = arduino
board_build.variant = generic_f103c
board_build.mcu = stm32f103c8t6
lib_deps =
  MIDIUSB
  EEPROM
monitor_speed = 115200
build_unflags = -Wl,--entry=Reset_Handler
build_flags =
  -D USB_MIDI_BUILD
