[env:bluepill_f103c8]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
lib_deps =
  MIDIUSB
build_unflags = -Wl,--entry=Reset_Handler
board_build.variant = generic_f103c
monitor_speed = 115200
